define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Location generated by Appery.io
     * @module Location
     */

    APP.controller('Location', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function clickGo
         */
        $scope.clickGo = function() {
            //On load screen logic
            Apperyio.navigateTo("Categories", {});

        };

        /**
         * user controller variables
         */
    }

});