define(['require'], function(require) {

    /**
     * Controller for index generated by Appery.io
     * @module index
     */

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */

        function init() {
            Apperyio.navigateTo("Location", {});

        };

        /**
         * user controller variables
         */
    }

    return ['$scope', 'Apperyio', controller];

});