define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Categories generated by Appery.io
     * @module Categories
     */

    APP.controller('Categories', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function clickEducation
         */
        $scope.clickEducation = function() {
            Apperyio.navigateTo("Education", {});
        };

        /**
         * @function clickSettings
         */
        $scope.clickSettings = function() {
            Apperyio.navigateTo("Settings", {});

        };

        /**
         * @function clickBack
         */
        $scope.clickBack = function() {
            Apperyio.navigateTo("Location", {});

        };

        /**
         * user controller variables
         */
    }

});