define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Tutorpage generated by Appery.io
     * @module Tutorpage
     */

    APP.controller('Tutorpage', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function clickAlgebra
         */
        $scope.clickAlgebra = function() {
            //On load screen logic
            Apperyio.navigateTo("detailtutor", {});

        };

        /**
         * user controller variables
         */
    }

});