define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Education generated by Appery.io
     * @module Education
     */

    APP.controller('Education', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function clickTutor
         */
        $scope.clickTutor = function() {
            //On load screen logic
            Apperyio.navigateTo("Tutorpage", {});

        };

        /**
         * @function clickFinance
         */
        $scope.clickFinance = function() {
            Apperyio.navigateTo("finance", {});

        };

        /**
         * @function clickBack
         */
        $scope.clickBack = function() {
            Apperyio.navigateTo("Categories", {});

        };

        /**
         * user controller variables
         */
    }

});