define(['require'], function(require) {
    /**
     * Routing configuration generated by Appery.io
     */

    /**
     * Default route
     * @type {{redirectTo: string}}
     */
    var default_route = {
        redirectTo: '/Location.html'
    };

/**
     * Routing configuration object
     * @property {object} default                               - Default routing configuration
     * @property {string} default.redirectTo                    - Default routing URL
     * @property {object} when                                  - Routing configuration for different URLs
     * @property {object} when./                                - Routing configuration for "/" URL
     * @property {string} when./.redirectTo                     - Redirect to default routing URL
     * @property {object} when["/Categories.html"]    - Routing configuration for /Categories.html URL
     * @property {string} when["/Categories.html"].c  - Controller for /Categories.html URL
     * @property {string} when["/Categories.html"].t  - Template for /Categories.html URL
     * @property {string[]} when["/Categories.html"].d  - Dependencies for /Categories.html URL
     * @property {object} when["/Screen2.html"]    - Routing configuration for /Screen2.html URL
     * @property {string} when["/Screen2.html"].c  - Controller for /Screen2.html URL
     * @property {string} when["/Screen2.html"].t  - Template for /Screen2.html URL
     * @property {string[]} when["/Screen2.html"].d  - Dependencies for /Screen2.html URL
     * @property {object} when["/Screen3.html"]    - Routing configuration for /Screen3.html URL
     * @property {string} when["/Screen3.html"].c  - Controller for /Screen3.html URL
     * @property {string} when["/Screen3.html"].t  - Template for /Screen3.html URL
     * @property {string[]} when["/Screen3.html"].d  - Dependencies for /Screen3.html URL
     * @property {object} when["/Screen4.html"]    - Routing configuration for /Screen4.html URL
     * @property {string} when["/Screen4.html"].c  - Controller for /Screen4.html URL
     * @property {string} when["/Screen4.html"].t  - Template for /Screen4.html URL
     * @property {string[]} when["/Screen4.html"].d  - Dependencies for /Screen4.html URL
     * @property {object} when["/Location.html"]    - Routing configuration for /Location.html URL
     * @property {string} when["/Location.html"].c  - Controller for /Location.html URL
     * @property {string} when["/Location.html"].t  - Template for /Location.html URL
     * @property {string[]} when["/Location.html"].d  - Dependencies for /Location.html URL
     * @property {object} when["/Education.html"]    - Routing configuration for /Education.html URL
     * @property {string} when["/Education.html"].c  - Controller for /Education.html URL
     * @property {string} when["/Education.html"].t  - Template for /Education.html URL
     * @property {string[]} when["/Education.html"].d  - Dependencies for /Education.html URL
     * @property {object} when["/Tutorpage.html"]    - Routing configuration for /Tutorpage.html URL
     * @property {string} when["/Tutorpage.html"].c  - Controller for /Tutorpage.html URL
     * @property {string} when["/Tutorpage.html"].t  - Template for /Tutorpage.html URL
     * @property {string[]} when["/Tutorpage.html"].d  - Dependencies for /Tutorpage.html URL
     * @property {object} when["/detailtutor.html"]    - Routing configuration for /detailtutor.html URL
     * @property {string} when["/detailtutor.html"].c  - Controller for /detailtutor.html URL
     * @property {string} when["/detailtutor.html"].t  - Template for /detailtutor.html URL
     * @property {string[]} when["/detailtutor.html"].d  - Dependencies for /detailtutor.html URL
     * @property {object} when["/finance.html"]    - Routing configuration for /finance.html URL
     * @property {string} when["/finance.html"].c  - Controller for /finance.html URL
     * @property {string} when["/finance.html"].t  - Template for /finance.html URL
     * @property {string[]} when["/finance.html"].d  - Dependencies for /finance.html URL
     * @property {object} when["/Settings.html"]    - Routing configuration for /Settings.html URL
     * @property {string} when["/Settings.html"].c  - Controller for /Settings.html URL
     * @property {string} when["/Settings.html"].t  - Template for /Settings.html URL
     * @property {string[]} when["/Settings.html"].d  - Dependencies for /Settings.html URL

     * @property {object} otherwise                             - Routing configuration for another URL
     * @property {object} otherwise.redirectTo                  - Redirect to default routing URL
     * @property {object} route_names                           - Route aliases
     * @property {string} route_names.["Categories"]  - "Categories" is an alias for "/Categories.html" routing
     * @property {string} route_names.["Screen2"]  - "Screen2" is an alias for "/Screen2.html" routing
     * @property {string} route_names.["Screen3"]  - "Screen3" is an alias for "/Screen3.html" routing
     * @property {string} route_names.["Screen4"]  - "Screen4" is an alias for "/Screen4.html" routing
     * @property {string} route_names.["Location"]  - "Location" is an alias for "/Location.html" routing
     * @property {string} route_names.["Education"]  - "Education" is an alias for "/Education.html" routing
     * @property {string} route_names.["Tutorpage"]  - "Tutorpage" is an alias for "/Tutorpage.html" routing
     * @property {string} route_names.["detailtutor"]  - "detailtutor" is an alias for "/detailtutor.html" routing
     * @property {string} route_names.["finance"]  - "finance" is an alias for "/finance.html" routing
     * @property {string} route_names.["Settings"]  - "Settings" is an alias for "/Settings.html" routing

     */
    return {
    default:
        default_route, when: {
            '/': default_route,
            '/Categories.html': {
                c: '$Categories/CategoriesController',
                t: '$Categories/CategoriesTemplate.html',
                d: []
            },
            '/Location.html': {
                c: '$Location/LocationController',
                t: '$Location/LocationTemplate.html',
                d: []
            },
            '/Education.html': {
                c: '$Education/EducationController',
                t: '$Education/EducationTemplate.html',
                d: []
            },
            '/Tutorpage.html': {
                c: '$Tutorpage/TutorpageController',
                t: '$Tutorpage/TutorpageTemplate.html',
                d: []
            },
            '/detailtutor.html': {
                c: '$detailtutor/detailtutorController',
                t: '$detailtutor/detailtutorTemplate.html',
                d: []
            },
            '/finance.html': {
                c: '$finance/financeController',
                t: '$finance/financeTemplate.html',
                d: []
            },
            '/Settings.html': {
                c: '$Settings/SettingsController',
                t: '$Settings/SettingsTemplate.html',
                d: []
            }

        },
        otherwise: default_route,
        route_names: {
            'Categories': '/Categories.html',
            'Screen2': '/Screen2.html',
            'Screen3': '/Screen3.html',
            'Screen4': '/Screen4.html',
            'Location': '/Location.html',
            'Education': '/Education.html',
            'Tutorpage': '/Tutorpage.html',
            'detailtutor': '/detailtutor.html',
            'finance': '/finance.html',
            'Settings': '/Settings.html'

        }
    };
});