define(['require', 'app'], function(require, APP) {

    /**
     * Controller for finance generated by Appery.io
     * @module finance
     */

    APP.controller('finance', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * @function clickBack
         */
        $scope.clickBack = function() {
            Apperyio.navigateTo("Education", {});

        };

        /**
         * user controller variables
         */
    }

});